// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUrWS-erpxxFMdMvwhY2EodwmT5F-uMWs',
    appId: '1:521079573627:web:ac372fb6860580d6d4a6de',
    messagingSenderId: '521079573627',
    projectId: 'cariocapark-20c9f',
    authDomain: 'cariocapark-20c9f.firebaseapp.com',
    storageBucket: 'cariocapark-20c9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWSrniHac8nQrIGD1GRUPTtdO-leoYznk',
    appId: '1:521079573627:android:9161c41f4f890ca9d4a6de',
    messagingSenderId: '521079573627',
    projectId: 'cariocapark-20c9f',
    storageBucket: 'cariocapark-20c9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkTTBh4zCE-A8ff7-6jg2Pe10MU83MXvc',
    appId: '1:521079573627:ios:d9877388916f667bd4a6de',
    messagingSenderId: '521079573627',
    projectId: 'cariocapark-20c9f',
    storageBucket: 'cariocapark-20c9f.firebasestorage.app',
    iosBundleId: 'com.example.cariocapark2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkTTBh4zCE-A8ff7-6jg2Pe10MU83MXvc',
    appId: '1:521079573627:ios:d9877388916f667bd4a6de',
    messagingSenderId: '521079573627',
    projectId: 'cariocapark-20c9f',
    storageBucket: 'cariocapark-20c9f.firebasestorage.app',
    iosBundleId: 'com.example.cariocapark2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUrWS-erpxxFMdMvwhY2EodwmT5F-uMWs',
    appId: '1:521079573627:web:20dc990ab6191a82d4a6de',
    messagingSenderId: '521079573627',
    projectId: 'cariocapark-20c9f',
    authDomain: 'cariocapark-20c9f.firebaseapp.com',
    storageBucket: 'cariocapark-20c9f.firebasestorage.app',
  );
}
